version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo python setup.py install

      - run:
          name: Run Tests
          command: |
            antmonitor/index.py --help

  test:
    docker:
      - image: circleci/python:3.6.4

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo pip install pycodestyle

      - run:
          name: Run Tests
          command: |
            pycodestyle --statistics --show-source . --ignore E501

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
