version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo pip install pycodestyle

      - run:
          name: run tests
          command: |
            pycodestyle .
